/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codefornature;

import java.awt.Desktop;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.PriorityQueue;
import java.util.Scanner;

/**
 *
 * @author ACER
 */
public class NewsSection extends javax.swing.JFrame {
    private final Home HomeFrameReference;
    private String username;
    private PriorityQueue<News> list=new PriorityQueue<>(Collections.reverseOrder());
    PriorityQueue<News> list2;
   
    public NewsSection(Home HomeFrame,String username) {
        this.HomeFrameReference=HomeFrame;
        this.username=username;
        initComponents();
        readFile();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();
        linkBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        linkTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 750));
        setMinimumSize(new java.awt.Dimension(1000, 750));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("TOP 5 NEWS ABOUT NATURE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("D:\\UM\\Y1\\S1\\FOP\\CodeForNature\\src\\icon\\back.jpg")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        textArea1.setBackground(new java.awt.Color(204, 204, 204));
        textArea1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        textArea1.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(textArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 710, 550));

        linkBtn.setBackground(new java.awt.Color(204, 255, 204));
        linkBtn.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        linkBtn.setForeground(new java.awt.Color(0, 102, 102));
        linkBtn.setText("OK");
        linkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(linkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 440, 70, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Go to Link ...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, -1, -1));

        linkTF.setBackground(new java.awt.Color(204, 204, 204));
        linkTF.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        linkTF.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(linkTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\UM\\Y1\\S1\\FOP\\CodeForNature\\src\\icon\\news bg.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        this.HomeFrameReference.setVisible(true);
        HomeFrameReference.pack();
        HomeFrameReference.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void linkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBtnActionPerformed
        try{
            int count=1;
            while(!list2.isEmpty()){
                if(count==Integer.parseInt(linkTF.getText())){
                    Desktop.getDesktop().browse(new URI(list2.peek().getLink()));
                    break;
                }
                list2.poll();
                count++;
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_linkBtnActionPerformed

    private void readFile() {
        try{
            Scanner read=new Scanner(new FileReader("NewsSample.txt"));
            while(read.hasNextLine()){
                String title=read.nextLine();
                String link=read.nextLine();
                String date=read.nextLine();
                
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d MMM yyyy", java.util.Locale.ENGLISH);
                LocalDate localDate=LocalDate.parse(date,formatter);
                
                if(title.contains("nature")||title.contains("Nature")){
                    list.add(new News(title,link,localDate));
                }
                
               if(read.hasNextLine()){
                    read.nextLine(); // Skip the empty line between records
               }
            }
            read.close();
            list2=new PriorityQueue<>(list);
            
            int count=1;
            StringBuilder sb=new StringBuilder();
            while(!list.isEmpty()){
                sb.append("["+(count++)+"] ");
                sb.append(list.poll().toString());
            }
            textArea1.setText(sb.toString());
        }
        catch(IOException e){
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton linkBtn;
    private javax.swing.JTextField linkTF;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables

    

}
